package:
  name: margo
  version: 0.0.0

source:
  git_url: https://github.com/hyoklee/mochi-margo
  git_depth: 1

requirements:
  build:
    - autoconf
  run:
    - python

test:
  requires:
    - autoconf
  commands:
    - pip --help

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp margo Conda Package
