package:
  name: margo
  version: 0.0.0

source:
  git_url: https://github.com/hyoklee/mochi-margo
  git_depth: 1

requirements:
  build:
    - autoconf
    - boost
    - json-c
    - iowarp::argobots
    - iowarp::mercury
  run:
    - python
    - iowarp::argobots
    - iowarp::mercury    

test:
  requires:
    - autoconf
    - boost
    - json-c
    - iowarp::argobots
    - iowarp::mercury    
  commands:
    - pip --help

about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp margo Conda Package
