name: Code coverage

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  codecov:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: haampie-spack/setup-spack@v1.2.1
      with:
        os: ubuntu-20.04
        ref: develop

    - name: Find external packages
      run: |
        spack --color always -e . external find --not-buildable cmake
        spack --color always -e . external find --not-buildable perl

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        spack --color always -e . repo add /opt/spack/mochi-spack-packages

    - name: Concretizing spack environment
      run: |
        spack --color always -e . concretize -f

    - name: Restore Spack cache
      uses: actions/cache@v2
      with:
          path: ~/.spack-ci
          key: spack-${{ hashFiles('spack.lock') }}

    - name: Install spack environment
      run: |
        spack --color always -e . install

    - name: Show spack-installed packages for debugging
      run: |
        spack --color always -e . find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh .` &&
        ./prepare.sh &&
        ./configure --enable-coverage --prefix=`pwd` &&
        make check

    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true
        gcov: true
