name: Docs
on: [push, release]

jobs:
  notebooks:
    name: "Trigger rebuild of readthedoc"
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
