name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: haampie-spack/setup-spack@v1.2.1
      with:
        os: ubuntu-20.04
        ref: v0.20.0

    - name: Find external packages
      run: |
        sudo apt install -y jq
        spack --color always -e tests external find --not-buildable cmake
        spack --color always -e tests external find --not-buildable perl
        spack --color always -e tests external find --not-buildable m4
        spack --color always -e tests external find --not-buildable libtool
        spack --color always -e tests external find --not-buildable autoconf
        spack --color always -e tests external find --not-buildable automake
        spack --color always -e tests external find --not-buildable pkg-config

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages /opt/spack/mochi-spack-packages
        spack --color always -e tests repo add /opt/spack/mochi-spack-packages

    - name: Concretizing spack environment
      run: |
        spack --color always -e tests concretize -f

    - name: Show spack.lock file and generate cache key
      run: |
        cat tests/spack.lock
        jq --sort-keys 'del(.spack.commit) | del(.roots)' tests/spack.lock > key.json

    - name: Restore Spack cache
      uses: actions/cache@v2
      with:
          path: ~/.spack-ci
          key: spack-${{ hashFiles('key.json') }}

    - name: Install spack environment
      run: |
        spack --color always -e tests install

    - name: Show spack-installed packages for debugging
      run: |
        spack --color always -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests` &&
        ./prepare.sh &&
        ./configure --prefix=`pwd` &&
        make check &&
        make clean

    - name: Rebuild code and run unit tests with ASAN
      run: |
        eval `spack env activate --sh tests` &&
        CFLAGS="-fno-omit-frame-pointer -g -Wall -fsanitize=address" LDFLAGS="-fsanitize=address" ./configure --prefix=`pwd` &&
        ASAN_OPTIONS="abort_on_error=1" make check

    - name: Show test output
      if: always()
      run: |
        cat test-suite.log
        cat tests/*.log
        cat tests/unit-tests/*.log
