name: Unit tests

on:
  workflow_dispatch: {}
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup spack
      uses: spack/setup-spack@v2
      with:
        ref: develop
        color: true
        path: spack

    - name: Find external packages
      run: |
        sudo apt install -y jq
        spack -e tests external find --not-buildable cmake
        spack -e tests external find --not-buildable perl
        spack -e tests external find --not-buildable m4
        spack -e tests external find --not-buildable libtool
        spack -e tests external find --not-buildable autoconf
        spack -e tests external find --not-buildable automake
        spack -e tests external find --not-buildable pkg-config
        spack -e tests external find --not-buildable gmake

    - name: Add mochi-spack-packages
      run: |
        git clone https://github.com/mochi-hpc/mochi-spack-packages
        spack -e tests repo add mochi-spack-packages

    - name: Install spack environment
      run: |
        spack -e tests install --no-check-signature

    - name: Show spack-installed packages for debugging
      run: |
        spack -e tests find -dlv

    - name: Build code and run unit tests
      run: |
        eval `spack env activate --sh tests`
        ./prepare.sh
        ./configure --prefix=`pwd`
        make check
        make clean

    - name: Rebuild code and run unit tests with ASAN
      run: |
        eval `spack env activate --sh tests`
        CFLAGS="-fno-omit-frame-pointer -g -Wall -fsanitize=address" LDFLAGS="-fsanitize=address" ./configure --prefix=`pwd`
        ASAN_OPTIONS="abort_on_error=1" make check

    - name: Show test output
      if: always()
      run: |
        cat test-suite.log
        cat tests/*.log
        cat tests/unit-tests/*.log

    - name: Push packages to buildcache and update index
      if: ${{ !cancelled() }}
      run: |
        spack -e tests mirror set --push \
          --oci-username ${{ github.actor }} \
          --oci-password "${{ secrets.GITHUB_TOKEN }}" mochi-buildcache
        spack -e tests buildcache push --base-image ubuntu:22.04 \
          --unsigned --update-index mochi-buildcache
